### ISSUE TITLE
Upgrading the plugin when the new version has new settings loses old settings values

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/MyBB_Thank-you-like-plugin#168]
Currently, the only way to gain access to new settings in a new version of the plugin is to first uninstall the plugin before copying the new files and reinstalling it, however, uninstalling the plugin causes all of its settings (including their values) to be lost. This is not so user-friendly, and it would be better for us provide a way for admins to upgrade without having to re-enter their settings values afterwards.

**Comment by lairdshaw** [comment]
In [a comment on another issue](https://github.com/Eldenroot/MyBB_Thank-you-like-plugin/pull/164#issuecomment-403239745), @Eldenroot wrote:

> maybe use "update" script as MyFacebook connect and others plugin?

That seems like a good approach. I had been considering a couple of other approaches - (1) retain all settings when the admin clicks "NO" at uninstall time, and (2) adding a setting to determine the data-retention policy at uninstall time - but I prefer the approach you've suggested.

**Comment by Eldenroot** [comment]
In my opinion "upgrade" script is the best approach - many plugin devs use that - for example Shade for all his plugins, dragonexpert for his recentthread plugin etc.

I will assign you to this issue, good idea, thank you!
