### ISSUE TITLE
Alerts lost (orphaned) on deactivation

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/MyBB_Thank-you-like-plugin#177]
When this plugin is integrated with MyAlerts, deactivating it deletes its MyAlert type, orphaning any existing alerts of that type in the database - and reactivating the plugin doesn't restore access to those alerts, because when the MyAlert type is recreated, it has a different ID.

**Comment by lairdshaw** [comment]
Perhaps unintegrating with MyAlerts should only be performed on uninstallation rather than deactivation, and only when "YES" is selected to delete all data, in which case, the orphaned alerts should be deleted too.

**Comment by lairdshaw** [comment]
This also has implications for the new upgrade procedure: we are instructing admins to first deactivate the plugin, which will trigger this issue.

**Comment by Eldenroot** [comment]
Ok, I agree. Integration should be performed only during instal. and deleted on plugin uninstal.

**Comment by lairdshaw** [comment]
I'm glad you agree. One other thing: currently, integrating with MyAlerts is forbidden when the tyl system is disabled via its Enable/Disable setting, even if both plugins are installed and activated. This seems to me to be a needless restriction. Happy for me to remove it?

**Comment by lairdshaw** [comment]
(To clarify: the restriction also only applies if the two plugins are not *already* integrated).

**Comment by Eldenroot** [comment]
Ok, I agree again :) So the best way is that integration will be deleted only on uninstall?

**Comment by lairdshaw** [comment]
Yep, the tyl alert type and any of its alerts will only be deleted on uninstall when selecting "Yes" to delete all data.

Integration will be possible by clicking the same link as currently exists in the Plugins module ("Click HERE to integrate the Thank You/Like System with MyAlerts") when (1) both plugins are installed and activated and (2) they are not yet integrated.

Will add to README.md a workaround (some SQL to run directly on the DB) so that admins can reclaim tyl alerts after using the new upgrade path.

**Comment by lairdshaw** [comment]
Also will try to simplify the instructions in README.md - I didn't realise how verbose I'd made it.
