### ISSUE TITLE
Do we need the tyl_tnumtyls column in the threads table?

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/MyBB_Thank-you-like-plugin#194]
Unless I'm missing something, the only time this column's value is used/referenced (as opposed to being set/updated) is in thankyoulike_delete_thread(), to check whether the deleted thread has any tyls. The only reason I can see to perform this check is for efficiency, but that seems like a poor reason: threads are only rarely deleted, and the efficiency savings are in any case very minor, and possibly outweighed by all of the calculations and updates that have to be performed to keep this column's value accurate.

Dropping this column and any code associated with it would reduce complexity and the possibility of forgetting to take it into account. I *did* fail to take it into account in commit 8b22b79b5e9fca12c2e243305a7cd1101d3945c2 which fixed #147: Likes/Thanks are not merged upon User ID merge, so even if we decide not to drop the column, we'll need to fix tyl_user_users_merge_commit() to take it into account.

**Comment by Eldenroot** [comment]
So I am a little bit confused - what is the side-effect of removing this column? Mainly on boards where threads are deleted (not only locked or soft deleted). On my board we delete some outdated content which has no value to users...

**Comment by lairdshaw** [comment]
There would be no side-effect in terms of the plugin's functionality and correctness: the plugin would do exactly the same job from the perspective of users and admins; thread deletions would still call the same hook which would perform the same task - it would just do so without an unnecessary and redundant check.

From the coders' (our) perspective, the code would be a little simpler and easier to maintain.

**Comment by Eldenroot** [comment]
Ok, so feel free to work on it. Simple code is better for maintaining :) as you wrote.

**Comment by lairdshaw** [comment]
Done. And btw, I understand your earlier confusion - my original description didn't make it clear enough that the proposed changes wouldn't affect functionality.

**Comment by Eldenroot** [comment]
No problem :) thank you
