### ISSUE TITLE
Top rated post - member profile- max width is broken if the post contain mycode

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/MyBB_Thank-you-like-plugin#195]
![image](https://user-images.githubusercontent.com/778890/43045592-c33355a8-8dbb-11e8-998a-fe8b975ae4d2.png)

this bug occurs even mycode is enabled/disabled in TYL setting page.

**Comment by lairdshaw** [comment]
Can you be more specific as to what the problem is? Maybe edit the image to indicate what/where the problem is? I'm struggling to see anything broken in the image. Have locally tested a trophy post with MyCode in it and can't see anything problematic about it on the profile page.

**Comment by Eldenroot** [comment]
Are online on any "common" chat software? We have our private chat channel for MyBB Group. Here is the link, or tell me if there is any other way how to contact you faster than via GitHub.

https://discord.gg/S9NvDTk

I will be back in 75-90 minutes, just going to buy some food to a local market.

**Comment by Eldenroot** [comment]
Here - default template code bundled with plugin (just changed some colors via CSS). When you display post content via `{$memprofile['tylmessage']}` check my previous image, the right half is just  too wide. Without `{$memprofile['tylmessage']}` (deleted from template just for testing purpose), the width is fine, 50%.
 ![image](https://user-images.githubusercontent.com/778890/43045749-df3a39c6-8dbe-11e8-8d9c-2dae24646062.png)

When you dont use any MyCode, the output is fine
![image](https://user-images.githubusercontent.com/778890/43045775-2054fd6a-8dbf-11e8-9a22-ed02299ad450.png)

I dont see any CSS missing atribute or missing tag, I will try to debug when I arrive home.

**Comment by lairdshaw** [comment]
Have sent you a PM on the MyBB community forums.

**Comment by Eldenroot** [comment]
Ok, I successfully debugged this issue. If you set to display unlimited length of post and the post contains attachments (images) -> it breaks the output in a user's member profile page. Deleting attachments did the trick, and the output looks fine.

**Comment by lairdshaw** [comment]
Good work, I'm glad you solved it. Maybe another possible solution is to set a max width on images in the member profile.

**Comment by Eldenroot** [comment]
I tried but without success. Need to figure it out.

**Comment by lairdshaw** [comment]
Hmm, I still can't replicate this on a vanilla 1.8.17 installation - and the image I'm using in the post is 3088 pixels wide! Maybe try for yourself on a vanilla install and then narrow down the differences between that and your customised site?

**Comment by Eldenroot** [comment]
Do you use image as an attachment, not inage via url. Try to add more pictures and unlimited lengh

**Comment by lairdshaw** [comment]
Oh, I was using via URL, but adding images as an attachment didn't make any difference - still couldn't replicate the issue (and the images didn't even display on the member profile - whether or not MyCode was enabled, all that showed was [attachment=1] etc).

The only way I can get the width of the trophy post to exceed 50% is by using a long, unbroken line of characters in the post.

**Comment by Eldenroot** [comment]
This can be fixed by css, I made a PR for reputation system in MyBB core few months ago where same issue was spotted.

I can only reproduce when the post has images as attachments, there must be something wrong on my side.

**Comment by lairdshaw** [comment]
OK. If you like, you can PM me the exact contents of the post (plus links to images for me to add as attachments) and I'll see if I can reproduce the issue by using exactly the same content as you're using.

**Comment by SvePu** [comment]
@Eldenroot 
Please make sure that you have scaleimages img CSS defination in global.css of forum theme.
e.g.:
```
.scaleimages img {
	max-width: 100%;
}
```

**Comment by Eldenroot** [comment]
@SvePu - yes, I use something like this:
`.scaleimages img {
	max-width: 600px;
}`

**Comment by Eldenroot** [comment]
I made a PR, which should solve the issue. At least works for me. Thank you for your time guys, one bug less :)

**Comment by lairdshaw** [comment]
Confirmed as working here too (for a long, unbroken line of characters - &lt;hr&gt; didn't seem to have caused any problems in the first place on my setup). Nicely fixed!
