### ISSUE TITLE
Sanitize Post/Thread Subjects in member profile

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/MyBB_Thank-you-like-plugin#200]
There is a small XSS vulnerability for most thanked/liked post in a member profile. 

Post/threads subjects are not sanitised.

**Comment by Eldenroot** [comment]
PR opened - #199

**Comment by SvePu** [comment]
Normally we didn't need this sanitizing...post subject are already clean and save because the member profile table is only an output of stored db entries.

**Comment by lairdshaw** [comment]
Are post/thread subjects sanitised before being stored in the DB though, @SvePu? It looks to me that they aren't. This looks like a genuine issue to me.

**Comment by Eldenroot** [comment]
If it is only an extra layer of "protection" and has no side-effect for a plugin, we can merge it.

**Comment by lairdshaw** [comment]
Is that a question for me, @SvePu or both of us? If it's for me: yes, I think we can merge it.
