### ISSUE TITLE
Move {$post['styleclass']} to allow see background color of post

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/MyBB_Thank-you-like-plugin#202]
We should move `{$post['styleclass']}` from `<div class="post{$post['styleclass']} {$unapproved_shade}" style="{$post_visibility}" id="post_{$post['pid']}">`

to 
`<div class="post_content{$post['styleclass']}">`

Why? Because users cannot see if the "highligted" post is selected/deleted or whatever, the background is still green.

@lairdshaw - please can you make a PR for that? Thank you! P.S. No rush :)

**Comment by lairdshaw** [comment]
Would be happy to review your PR, @Eldenroot - you seem to understand the problem+solution already. Won't be able to do it for a few days though as am away from home.

**Comment by Eldenroot** [comment]
I had a small issue that I was unable to make it working properly - install/uninstall doesnt remove this, I edited it but without success. If you will have some free time to look at this issue, would be nice. IT should be something like this:

`{$ignore_bit}{$deleted_bit}
<a name="pid{$post['pid']}" id="pid{$post['pid']}"></a>
<div class="post classic {$unapproved_shade}" style="{$post_visibility}" id="post_{$post['pid']}">
<div class="post_author scaleimages">
{$post['useravatar']}
<div class="author_information">
<strong><span class="largetext">{$post['profilelink']}</span></strong><br />
				{$post['groupimage']}
				{$post['additional_images_html']}
<span style="text-align: center; padding-top: 2px;" class="userstar star_{$post['stars']}" title="{$post['usertitle']}"></span>
	</div>
	<div class="author_statistics">
{$post['user_details']}
	</div>
</div><div class="post_arrow"></div>
<div class="post_content{$post['styleclass']}">
	<div class="post_head" title="{$post['subject_title']}">
		{$post['posturl']}
		{$post['icon']} ..........`

**Comment by lairdshaw** [comment]
Have you updated the calls to `find_replace_templatesets` on lines 956 and 957 of inc/plugins/thankyoulike.php?

**Comment by Eldenroot** [comment]
There is no easy way how to replace it because there is no unique part of code to be replaced :( I will have a look again
