### ISSUE TITLE
Recount + Rebuild Issue

### ISSUE THREAD

**Issue by Anon69420** [mybbgroup/MyBB_Thank-you-like-plugin#203]
When trying to recount + rebuild my likes, all my likes disappear. Note, they are all still in the database.
![bc3e68ebc54e0ba28d35ded9ae7c5849](https://user-images.githubusercontent.com/43067376/45219288-5082de00-b2a2-11e8-8cd2-a0bef22bf2df.gif)

![56732a2543fa81ca224a66f80f1cc84a](https://user-images.githubusercontent.com/43067376/45219182-f97d0900-b2a1-11e8-8864-9812c90d35e5.png)

**Comment by Eldenroot** [comment]
Version of plugin + mybb version + php version? @lairdshawn

**Comment by Anon69420** [comment]
MyBB Version: 1.8.15
PHP Version: 5.4.45-0+deb7u12
Plugin Version: 1.9.11

**Comment by lairdshaw** [comment]
Can't reproduce here on MyBB 1.8.18 with plugin version 1.8.18. Plugin version 1.9.11 is very old though and I don't think we can support it. Possible to upgrade?

**Comment by Eldenroot** [comment]
Yeah, first of all we cannot and we wont support bug reports and technical issues for old versions of tyl plugin.

First of all update Mybb and then thank you like plugin and let us know the result. Thank you

**Comment by Eldenroot** [comment]
Please let us know :) New version brings a lot of bug fixes, improvements and new features, you wont regret!
