### ISSUE TITLE
Plugin Settings not showing Trophy Stat Settings

### ISSUE THREAD

**Issue by Anon69420** [mybbgroup/MyBB_Thank-you-like-plugin#204]
Good Afternoon!

It's me again, the Likes recount works again now after updating to the latest version. However, I am now having another issue after a failed MyBB update. Before attempting to update the Trophy System worked and I had the option in the Plugin Settings to alter it. After a failed attempt at updating the forum, I reverted to my original version of MyBB. However, this seems to have broken the plugin which no longer shows the trophy settings.

MyBB version: 1.8.15
TYLike Version: 3.1.0
![550a09d83cf652fb9c6d902c5fb80f9b](https://user-images.githubusercontent.com/43067376/45621443-32726600-ba78-11e8-8d56-546a8f40b9a9.gif)

**Comment by Eldenroot** [comment]
Hi, deactivate -> uninstall but DO NOT drop data from database -> install again

**Comment by Anon69420** [comment]
Yeah how do I do that without dropping the table :P

**Comment by Eldenroot** [comment]
Just click on "NO" when you will be asked during uninstall
