### ISSUE TITLE
BUG: Users cannot add thx/like to forums without a reply permission

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/MyBB_Thank-you-like-plugin#206]
https://community.mybb.com/thread-169382-post-1319394.html#pid1319394

I summon @lairdshaw :)

**Comment by lairdshaw** [comment]
Confirmed. We can delete `$forumpermissions['canpostreplys'] == 0 || ` from line 134 of /thankyoulike.php if we think this behaviour should be changed. Right now I can't see any reason not to.

**Comment by Eldenroot** [comment]
OK, or is there any reason why it is coded in that way? Right now we can select forums where voting is enabled, so I think it is enough. Or do you have any better idea how to solve this bug without removing this piece of code?

**Comment by lairdshaw** [comment]
Not sure why it was coded that way - it was like that from the second commit to this repository. Seems best to remove it.

**Comment by Eldenroot** [comment]
OK, I agree with you!
